version: '3.9'
services:
  redis-exporter:
    image: oliver006/redis_exporter
    container_name: redis_exporter_svc
    network_mode: host
    ports:
      - '9121:9121'
    volumes:
      - ./lua_scripts:/scripts
    entrypoint:  ["/redis_exporter"]
    command: >
      --script /scripts/export_run_id.lua

  prometheus:
    image: prom/prometheus:v2.41.0
    container_name: prometheus_db
    network_mode: host
    ports:
      - '9090:9090'
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus

volumes:
  prometheus_data:
