global:
  scrape_interval: 5s
scrape_configs:
  - job_name: redis_exporter
    static_configs:
    - targets: ['redis-exporter:9121']
  - job_name: kafka_exporter
    static_configs:
    - targets: ['kafka-exporter:9308']    
  - job_name: mysql_exporter
    static_configs:
    - targets: ['mysql-exporter:9104']    
