version: '3.9'

services:
  mysql-db-manager:
    container_name: phpMyadmin_app
    image: phpmyadmin/phpmyadmin
    ports:
      - 5051:80
    volumes:
      - ~/dockerPreset/phpmyadminData/config.user.inc.php:/etc/phpmyadmin/config/config.user.inc.php
    environment:
      - PMA_HOSTS=${PMA_HOSTS}
      - PMA_PORT=3306
    networks:
      - pma_remote

networks:
  pma_remote:
