version: "3.2"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    container_name: zookeeper
    tmpfs: "/datalog"
    volumes:
      - "zookeeper_data:/bitnami"
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:2.8.1
    container_name: kafka
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_INTER_BROKER_USER: user
      KAFKA_INTER_BROKER_PASSWORD: bitnami
      KAFKA_CFG_MAX_PARTITION_FETCH_BYTES: 1048576
      KAFKA_CFG_MAX_REQUEST_SIZE: 1048576
      KAFKA_CFG_BROKER_ID: 1
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:19092,PLAINTEXT_HOST://localhost:9092
      KAFKA_CFG_LISTENERS: PLAINTEXT://kafka:19092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CFG_ADVERTISED_HOST_NAME: kafka
      KAFKA_CFG_ADVERTISED_PORT: 9092
    volumes:
      - "kafka_data:/bitnami"
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
      
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui-nhost
    ports:
      - 8080:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:19092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

  kafka-init-topics:
    image: docker.io/bitnami/kafka:2.8.1
    depends_on:
      - zookeeper
      - kafka
      - kafka-ui
    command: "bash -c 'sleep 10 && \
                kafka-topics.sh --create --topic Errors --partitions 1 --replication-factor 1 --if-not-exists --bootstrap-server kafka:19092 && \
                kafka-topics.sh --create --topic GameProc --partitions 1 --replication-factor 1 --if-not-exists --bootstrap-server kafka:19092 && \
                kafka-topics.sh --create --topic UniversalProc --partitions 1 --replication-factor 1 --if-not-exists --bootstrap-server kafka:19092'"

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local