version: '3.9'
services:
    redis:
      image: redis:alpine
      command: redis-server --port 6379
      container_name: redis
      hostname: redis
      labels:
        - "name=redis"
        - "mode=standalone"
      ports:
        - 6379:6379
      volumes:
        - ~/dockerPreset/redisData:/data
      networks:
        - redis_local

networks:
  redis_local:
